/**
 * Application frame to create or edit a application
 */
package IHM.frameObject;


import data.IHM.DataIHM;
import java.awt.Toolkit;
import java.sql.Date;
import java.util.ArrayList;
import myObject.*;

/**
 *
 * @author Mary
 */
public class FrameApplication extends javax.swing.JFrame {
    private Application application = null;

    /**
     * Creates new form FrameApplication
     */
    public FrameApplication() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public FrameApplication(Application appliation) {
        initComponents();
        this.application = appliation;
        setIcon();
        loadValue();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabelValID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelResponsible = new javax.swing.JLabel();
        jComboBoxResponsible = new javax.swing.JComboBox();
        jLabelResponsibleDeputy = new javax.swing.JLabel();
        jComboBoxResponsibleDeputy = new javax.swing.JComboBox();
        jLabelResponsibleDevelopment = new javax.swing.JLabel();
        jComboBoxResponsibleDevelopment = new javax.swing.JComboBox();
        jLabelResponsibleOperation = new javax.swing.JLabel();
        jComboBoxResponsibleOperation = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabelsupportCapabilities = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSupportCapabilities = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jLabelProvidedInterfaces = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListProvidedInterfaces = new javax.swing.JList();
        jLabelUsedInterface = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListUsedInterface = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jLabelUsedTechnology = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListUsedTechnologie = new javax.swing.JList();
        jLabelHostBy = new javax.swing.JLabel();
        jComboBoxHostBy = new javax.swing.JComboBox();
        jLabelDatabaseUse = new javax.swing.JLabel();
        jComboBoxDatabaseUse = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabelInvestmentCost = new javax.swing.JLabel();
        jTextFieldInvestmentCost = new javax.swing.JTextField();
        jLabelOperatingCost = new javax.swing.JLabel();
        jTextFieldOperatingCost = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabelLifecycle = new javax.swing.JLabel();
        jComboBoxLifecycle = new javax.swing.JComboBox();
        jLabelProductionDate = new javax.swing.JLabel();
        jLabelDecommissionDate = new javax.swing.JLabel();
        jLabelInvestmentStrategy = new javax.swing.JLabel();
        jTextFieldInvestmentStrategy = new javax.swing.JTextField();
        jLabelReplace = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListReplace = new javax.swing.JList();
        jLabelReplacedBy = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jListReplacedBy = new javax.swing.JList();
        jCalendarComboBoxProductionDate = new de.wannawork.jcalendar.JCalendarComboBox();
        jCalendarComboBoxDecommissioningDate = new de.wannawork.jcalendar.JCalendarComboBox();
        jPanel9 = new javax.swing.JPanel();
        jLabelCategory = new javax.swing.JLabel();
        jTextFieldCategory = new javax.swing.JTextField();
        jLabelStrategicImportance = new javax.swing.JLabel();
        jTextFieldStrategicImportance = new javax.swing.JTextField();
        jLabelBusinessFit = new javax.swing.JLabel();
        jTextFieldBBusinessFit = new javax.swing.JTextField();
        jLabelITFit = new javax.swing.JLabel();
        jTextFieldITFit = new javax.swing.JTextField();
        jLabelCostFit = new javax.swing.JLabel();
        jTextFieldCostFit = new javax.swing.JTextField();
        jLabelNumberOfUser = new javax.swing.JLabel();
        jTextFieldNumberOfUser = new javax.swing.JTextField();
        jLabelSecurityAvailabitily = new javax.swing.JLabel();
        jTextFieldSecurityAvailability = new javax.swing.JTextField();
        jLabelSecurityConfidentiality = new javax.swing.JLabel();
        jTextFieldSecurityConfidentiality = new javax.swing.JTextField();
        jLabelSecurityIntegrity = new javax.swing.JLabel();
        jTextFieldSecurityIntegrity = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelName.setText("Non");

        jLabelID.setText("ID");

        jLabelType.setText("Type");

        jLabel4.setText("Description");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabelValID.setText("ValID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelValID))
                    .addComponent(jLabelID)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelType)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addComponent(jTextFieldType)
                        .addComponent(jLabelName)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValID)
                .addGap(22, 22, 22)
                .addComponent(jLabelType)
                .addGap(8, 8, 8)
                .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General Information", jPanel1);

        jLabelResponsible.setText("Responsable");

        jComboBoxResponsible.setModel(new javax.swing.DefaultComboBoxModel(DataIHM.loadResponsible()));

        jLabelResponsibleDeputy.setText("Responsable suppléant");

        jComboBoxResponsibleDeputy.setModel(new javax.swing.DefaultComboBoxModel(DataIHM.loadResponsible()));

        jLabelResponsibleDevelopment.setText("Responsable développement");

        jComboBoxResponsibleDevelopment.setModel(new javax.swing.DefaultComboBoxModel(DataIHM.loadResponsible()));

        jLabelResponsibleOperation.setText("Responsable Opération");

        jComboBoxResponsibleOperation.setModel(new javax.swing.DefaultComboBoxModel(DataIHM.loadResponsible()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResponsibleOperation)
                    .addComponent(jLabelResponsibleDevelopment)
                    .addComponent(jLabelResponsibleDeputy)
                    .addComponent(jLabelResponsible)
                    .addComponent(jComboBoxResponsible, 0, 200, Short.MAX_VALUE)
                    .addComponent(jComboBoxResponsibleDeputy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxResponsibleDevelopment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxResponsibleOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelResponsible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxResponsible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelResponsibleDeputy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxResponsibleDeputy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelResponsibleDevelopment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxResponsibleDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelResponsibleOperation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxResponsibleOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Organisation", jPanel2);

        jLabelsupportCapabilities.setText("Ilot supporté");

        jListSupportCapabilities.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListSupportCapabilities);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelsupportCapabilities))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelsupportCapabilities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Architecture", jPanel4);

        jLabelProvidedInterfaces.setText("Interface fournis");

        jListProvidedInterfaces.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListProvidedInterfaces);

        jLabelUsedInterface.setText("Interface utilisé");

        jListUsedInterface.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jListUsedInterface);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProvidedInterfaces)
                            .addComponent(jLabelUsedInterface))
                        .addGap(0, 339, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProvidedInterfaces)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsedInterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Interfaces", jPanel5);

        jLabelUsedTechnology.setText("Technologie utilisé");

        jListUsedTechnologie.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jListUsedTechnologie);

        jLabelHostBy.setText("Serveur d'hebergement");

        jComboBoxHostBy.setModel(new javax.swing.DefaultComboBoxModel(data.IHM.DataIHM.getAllServer()));

        jLabelDatabaseUse.setText("Base de données liée");

        jComboBoxDatabaseUse.setModel(new javax.swing.DefaultComboBoxModel(data.IHM.DataIHM.getAllDatabase()));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUsedTechnology)
                            .addComponent(jLabelHostBy)
                            .addComponent(jLabelDatabaseUse)
                            .addComponent(jComboBoxDatabaseUse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxHostBy, 0, 200, Short.MAX_VALUE))
                        .addGap(0, 235, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsedTechnology)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHostBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxHostBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDatabaseUse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDatabaseUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Technology Compnets", jPanel6);

        jLabelInvestmentCost.setText("Coût d'investisement");

        jLabelOperatingCost.setText("Coût d'opération");

        jTextFieldOperatingCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOperatingCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInvestmentCost)
                    .addComponent(jTextFieldInvestmentCost, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabelOperatingCost)
                    .addComponent(jTextFieldOperatingCost))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInvestmentCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldInvestmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelOperatingCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOperatingCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cost", jPanel7);

        jLabelLifecycle.setText("Cycle de vie");

        jComboBoxLifecycle.setModel(new javax.swing.DefaultComboBoxModel(data.IHM.DataIHM.getAllLifecycle()));

        jLabelProductionDate.setText("Date de production");

        jLabelDecommissionDate.setText("Date de démantèlement");

        jLabelInvestmentStrategy.setText(" Stratégie d'investissement");

        jTextFieldInvestmentStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInvestmentStrategyActionPerformed(evt);
            }
        });

        jLabelReplace.setText("Remplace");

        jListReplace.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListReplace);

        jLabelReplacedBy.setText("Remplacé par");

        jListReplacedBy.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jListReplacedBy);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane9)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLifecycle)
                                    .addComponent(jComboBoxLifecycle, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jLabelProductionDate)
                                    .addComponent(jLabelDecommissionDate)
                                    .addComponent(jLabelInvestmentStrategy)
                                    .addComponent(jTextFieldInvestmentStrategy))
                                .addComponent(jLabelReplace)))
                        .addComponent(jLabelReplacedBy))
                    .addComponent(jCalendarComboBoxProductionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCalendarComboBoxDecommissioningDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLifecycle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxLifecycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelProductionDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarComboBoxProductionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabelDecommissionDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendarComboBoxDecommissioningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabelInvestmentStrategy)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldInvestmentStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelReplace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelReplacedBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lifecycle", jPanel8);

        jLabelCategory.setText("Catégorie");

        jLabelStrategicImportance.setText("Importance stratégique");

        jLabelBusinessFit.setText("Ajustement au business");

        jLabelITFit.setText("Ajustement  à l\"IT");

        jLabelCostFit.setText("Ajustement du coût");

        jLabelNumberOfUser.setText("Nombre d'utilisateur");

        jLabelSecurityAvailabitily.setText("Disponibilité");

        jLabelSecurityConfidentiality.setText("Confidentialité");

        jLabelSecurityIntegrity.setText("Intégrité");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCategory)
                    .addComponent(jTextFieldCategory)
                    .addComponent(jLabelStrategicImportance)
                    .addComponent(jTextFieldStrategicImportance)
                    .addComponent(jLabelBusinessFit)
                    .addComponent(jTextFieldBBusinessFit)
                    .addComponent(jLabelITFit)
                    .addComponent(jTextFieldITFit)
                    .addComponent(jLabelCostFit)
                    .addComponent(jTextFieldCostFit)
                    .addComponent(jLabelNumberOfUser)
                    .addComponent(jTextFieldNumberOfUser)
                    .addComponent(jLabelSecurityAvailabitily)
                    .addComponent(jTextFieldSecurityAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabelSecurityConfidentiality)
                    .addComponent(jTextFieldSecurityConfidentiality)
                    .addComponent(jLabelSecurityIntegrity)
                    .addComponent(jTextFieldSecurityIntegrity))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelStrategicImportance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldStrategicImportance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelBusinessFit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBBusinessFit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelITFit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldITFit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCostFit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCostFit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNumberOfUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNumberOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSecurityAvailabitily)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSecurityAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSecurityConfidentiality)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldSecurityConfidentiality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSecurityIntegrity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSecurityIntegrity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Classification", jPanel9);

        jButtonSave.setText("Enregistrer");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Annuler");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOperatingCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOperatingCostActionPerformed
        // TODO add your handling code here:
        //A supprimer
    }//GEN-LAST:event_jTextFieldOperatingCostActionPerformed

    private void jTextFieldInvestmentStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInvestmentStrategyActionPerformed
        // TODO add your handling code here:
        //A supprimer
    }//GEN-LAST:event_jTextFieldInvestmentStrategyActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        //A suprimmer
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * Save data of application
     * @param evt 
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:

        createApplication().createObject();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApplication().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBoxDecommissioningDate;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBoxProductionDate;
    private javax.swing.JComboBox jComboBoxDatabaseUse;
    private javax.swing.JComboBox jComboBoxHostBy;
    private javax.swing.JComboBox jComboBoxLifecycle;
    private javax.swing.JComboBox jComboBoxResponsible;
    private javax.swing.JComboBox jComboBoxResponsibleDeputy;
    private javax.swing.JComboBox jComboBoxResponsibleDevelopment;
    private javax.swing.JComboBox jComboBoxResponsibleOperation;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBusinessFit;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelCostFit;
    private javax.swing.JLabel jLabelDatabaseUse;
    private javax.swing.JLabel jLabelDecommissionDate;
    private javax.swing.JLabel jLabelHostBy;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelITFit;
    private javax.swing.JLabel jLabelInvestmentCost;
    private javax.swing.JLabel jLabelInvestmentStrategy;
    private javax.swing.JLabel jLabelLifecycle;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumberOfUser;
    private javax.swing.JLabel jLabelOperatingCost;
    private javax.swing.JLabel jLabelProductionDate;
    private javax.swing.JLabel jLabelProvidedInterfaces;
    private javax.swing.JLabel jLabelReplace;
    private javax.swing.JLabel jLabelReplacedBy;
    private javax.swing.JLabel jLabelResponsible;
    private javax.swing.JLabel jLabelResponsibleDeputy;
    private javax.swing.JLabel jLabelResponsibleDevelopment;
    private javax.swing.JLabel jLabelResponsibleOperation;
    private javax.swing.JLabel jLabelSecurityAvailabitily;
    private javax.swing.JLabel jLabelSecurityConfidentiality;
    private javax.swing.JLabel jLabelSecurityIntegrity;
    private javax.swing.JLabel jLabelStrategicImportance;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelUsedInterface;
    private javax.swing.JLabel jLabelUsedTechnology;
    private javax.swing.JLabel jLabelValID;
    private javax.swing.JLabel jLabelsupportCapabilities;
    private javax.swing.JList jListProvidedInterfaces;
    private javax.swing.JList jListReplace;
    private javax.swing.JList jListReplacedBy;
    private javax.swing.JList jListSupportCapabilities;
    private javax.swing.JList jListUsedInterface;
    private javax.swing.JList jListUsedTechnologie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldBBusinessFit;
    private javax.swing.JTextField jTextFieldCategory;
    private javax.swing.JTextField jTextFieldCostFit;
    private javax.swing.JTextField jTextFieldITFit;
    private javax.swing.JTextField jTextFieldInvestmentCost;
    private javax.swing.JTextField jTextFieldInvestmentStrategy;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumberOfUser;
    private javax.swing.JTextField jTextFieldOperatingCost;
    private javax.swing.JTextField jTextFieldSecurityAvailability;
    private javax.swing.JTextField jTextFieldSecurityConfidentiality;
    private javax.swing.JTextField jTextFieldSecurityIntegrity;
    private javax.swing.JTextField jTextFieldStrategicImportance;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables

   private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("usi.png")));
    }

    private void loadValue() {
        jCalendarComboBoxDecommissioningDate.setDate(application.getDecommissionDate());
        jCalendarComboBoxProductionDate.setDate(application.getProductionDate());
        jComboBoxDatabaseUse.setSelectedItem((Database) application.getDatabase());
        jComboBoxHostBy.setSelectedItem((Server) application.getServer());
        jComboBoxLifecycle.setSelectedItem((Lifecycle) application.getLifecycle());
        jComboBoxResponsible.setSelectedItem((Responsible) application.getResponsible());
        jComboBoxResponsibleDeputy.setSelectedItem((Responsible) application.getResponsibleDeputy());
        jComboBoxResponsibleDevelopment.setSelectedItem((Responsible) application.getResponsibleDevelopment());
        jComboBoxResponsibleOperation.setSelectedItem((Responsible) application.getResponsibleOperation());
        jLabelValID.setText(Integer.toString(application.getId()));
        jTextAreaDescription.setText(application.getDescription());
        jTextFieldBBusinessFit.setText(application.getFitBusiness());
        jTextFieldCategory.setText(application.getCategory());
        jTextFieldCostFit.setText(application.getFitCost());
        jTextFieldITFit.setText(application.getFitIT());
        jTextFieldInvestmentCost.setText(Integer.toString(application.getInvestmentCost()));
        jTextFieldInvestmentStrategy.setText(application.getInvestmentStrategy());
        jTextFieldName.setText(application.getName());
        jTextFieldNumberOfUser.setText(Integer.toString(application.getNumberUser()));
        jTextFieldOperatingCost.setText(Integer.toString(application.getOperatingCost()));
        jTextFieldSecurityAvailability.setText(application.getSecurityAvailability());
        jTextFieldSecurityConfidentiality.setText(application.getSecurityConfidentiality());
        jTextFieldSecurityIntegrity.setText(application.getSecurityIntegrity());
        jTextFieldStrategicImportance.setText(application.getStrategyImportance());
        jTextFieldType.setText(application.getTypeApplication());
        
    }

    private Application createApplication() {
         return new Application(jTextFieldName.getText(), jTextAreaDescription.getText(), 
            (Date) jCalendarComboBoxProductionDate.getDate() , jTextFieldType.getText(),
            (Responsible) jComboBoxResponsible.getSelectedItem(),(Responsible) jComboBoxResponsibleDeputy.getSelectedItem(),
            (Responsible) jComboBoxResponsibleOperation.getSelectedItem(), (Responsible) jComboBoxResponsibleDevelopment.getSelectedItem(),
            (Lifecycle) jComboBoxLifecycle.getSelectedItem(), (Database) jComboBoxDatabaseUse.getSelectedItem(), (Date) jCalendarComboBoxDecommissioningDate.getDate(), Integer.parseInt(jTextFieldInvestmentCost.getText()), jTextFieldInvestmentStrategy.getText(),
            Integer.parseInt(jTextFieldOperatingCost.getText()), Integer.parseInt(jTextFieldNumberOfUser.getText()),
            jTextFieldSecurityAvailability.getText(), jTextFieldSecurityConfidentiality.getText(),
            jTextFieldSecurityIntegrity.getText(),
            jTextFieldCategory.getText(), (Server) jComboBoxHostBy.getSelectedItem(),
            jTextFieldBBusinessFit.getText(), jTextFieldITFit.getText(), jTextFieldCostFit.getText(),
            jTextFieldStrategicImportance.getText(), (ArrayList<Capability>) jListSupportCapabilities.getModel(),
            (ArrayList<Application>) jListReplace.getModel(), (ArrayList<Application>) jListReplacedBy.getModel(), 
            (ArrayList<Interface>) jListProvidedInterfaces.getModel(), (ArrayList<Interface>) jListUsedInterface.getModel(), 
            (ArrayList<Technology>) jListUsedTechnologie.getModel()
        );
    }
}
